### ISSUE TITLE
Marketplace

### ISSUE THREAD

**Issue by yoannfleurydev** [yoannfleurydev/vscode-gitlab-merge-request-upvotes#1]
# Resource:

* https://marketplace.visualstudio.com/vscode

# TO-DO

* [ ] Design an Icon for the extension
* [ ] Check all the metadata for the extension
* [ ] Automate the release using GitHub Actions
